"""likesテーブルと外部キー修正

Revision ID: e85f5815717c
Revises: 
Create Date: 2025-07-24 22:55:50.875261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85f5815717c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('matched',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_likes_to_user_user', 'user', ['to_user'], ['id'])
        batch_op.create_foreign_key('fk_likes_from_user_user', 'user', ['from_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_to_user_user', type_='foreignkey')
        batch_op.drop_constraint('fk_likes_from_user_user', type_='foreignkey')
        batch_op.alter_column('matched',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
